In [1]:
import glob
import numpy as np
import pandas as pd

from pathlib import Path

csv_enums = glob.glob("./dataset/*")

column_translation = {
    "지점": "Station",
    "일시": "Date/Time",
    "기온(°C)": "Temperature (°C)",
    "1분 강수량(mm)": "1-minute Precipitation (mm)",
    "강수유무(유무)": "Precipitation Presence (Presence/Absence)",
    "풍향(deg)": "Wind Direction (deg)",
    "풍속(m/s)": "Wind Speed (m/s)",
    "현지기압(hPa)": "Local Pressure (hPa)",
    "해면기압(hPa)": "Sea-level Pressure (hPa)",
    "습도(%)": "Humidity (%)",
    "일사(MJ/m^2)": "Solar Radiation (MJ/m^2)",
    "일조(Sec)": "Sunshine Duration (Sec)",
}

def detect_encoding(file_path):
    """
    Try common Korean encodings.

    CP949 is commonly used for Korean meteorological CSV files.
    """
    file_path = Path(file_path)

    encodings = [
        "utf-8-sig",
        "utf-8",
        "cp949",
        "euc-kr",
    ]

    for encoding in encodings:
        try:
            with open(file_path, "r", encoding=encoding) as f:
                f.read(10000)

            return encoding

        except UnicodeDecodeError:
            continue

    raise UnicodeDecodeError(
        "unknown",
        b"",
        0,
        1,
        f"Could not determine encoding for {file_path}"
    )

# Load and Translate
monthly_data = dict()
for csv_enum in csv_enums:
    # Find Proper encoding to load korean
    encoding = detect_encoding(csv_enum)

    # Load CSV
    loaded_df = pd.read_csv(
        csv_enum, encoding=encoding, dtype=str, keep_default_na=False
    )

    # Translate
    translated_df = loaded_df.rename(columns=column_translation)
    
    key_month_name = pd.to_datetime(translated_df["Date/Time"]).dt.month_name()[0]

    # Store and sort based on months
    monthly_data[key_month_name] = translated_df

In [2]:
print(monthly_data.keys())
print(monthly_data['April'].keys())

dict_keys(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August'])
Index(['Station', 'Date/Time', 'Temperature (°C)',
       '1-minute Precipitation (mm)',
       'Precipitation Presence (Presence/Absence)', 'Wind Direction (deg)',
       'Wind Speed (m/s)', 'Local Pressure (hPa)', 'Sea-level Pressure (hPa)',
       'Humidity (%)', 'Solar Radiation (MJ/m^2)', 'Sunshine Duration (Sec)'],
      dtype='object')

In [3]:
monthly_data['April']['Solar Radiation (MJ/m^2)']

0
1
2
3
4
        ..
43194
43195
43196
43197
43198
Name: Solar Radiation (MJ/m^2), Length: 43199, dtype: object

In [4]:
monthly_data['April']

,Station,Date/Time,Temperature (°C),1-minute Precipitation (mm),Precipitation Presence (Presence/Absence),Wind Direction (deg),Wind Speed (m/s),Local Pressure (hPa),Sea-level Pressure (hPa),Humidity (%),Solar Radiation (MJ/m^2),Sunshine Duration (Sec)
0,939,2026-04-01 00:01,10.6,0,0,323.3,.8,1008.2,1014.2,78.3,,
1,939,2026-04-01 00:02,10.6,0,0,301,.7,1008.2,1014.2,78.5,,
2,939,2026-04-01 00:03,10.6,0,0,303.8,.2,1008.3,1014.3,78.9,,
3,939,2026-04-01 00:04,10.5,0,0,306.7,1.7,1008.3,1014.3,79.1,,
4,939,2026-04-01 00:05,10.6,0,0,334.4,2.1,1008.3,1014.3,79,,
...,...,...,...,...,...,...,...,...,...,...,...,...
43194,939,2026-04-30 23:56,11.7,0,10,288.3,.5,1004,1009.9,93.1,,
43195,939,2026-04-30 23:57,11.7,0,10,304.7,1.5,1004,1009.9,93.1,,
43196,939,2026-04-30 23:58,11.7,0,10,294.7,.7,1004,1009.9,93.2,,
43197,939,2026-04-30 23:59,11.7,0,10,287,.3,1004,1009.9,93.2,,
43198,939,2026-05-01 00:00,11.7,0,10,24.7,.1,1004,1009.9,93.1,,

In [5]:
N_STATES = 5
INITIAL_TRAIN_DAYS = 5
TRAIN_INTERVAL_DAYS = 5
HORIZON = 5
N_ITER = 50

In [6]:
from modules.evaluations import calculate_metrics
from modules.model import get_hmm_features, train_hmm, learn_state_scores, evaluate_day
from modules.feature_process import prepare_data, create_features, create_future_label
from modules.logging import setup_logging

from modules.debug import inspect_precipitation
from modules.export import save_evaluation_json

c:\Users\andro\.conda\envs\weather_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
import logging

output_dir, log_file = setup_logging(
    "./results/"
)
logging.info(
    "Starting HMM walk-forward experiment"
)

df = prepare_data(
    monthly_data
)
inspect_precipitation(df)
df = create_features(
    df,
    HORIZON=HORIZON
)

df = create_future_label(
    df,
    horizon=HORIZON,
    heat_center=31.0,
    heat_steepness=1.0,
)

df["_date"] = (
    df["Date/Time"]
    .dt.normalize()
)

dates = sorted(
    df["_date"]
    .drop_duplicates()
)

2026-08-25 18:48:11,767 | INFO | Starting HMM walk-forward experiment

=== PRECIPITATION CHECK ===

1-minute Precipitation (mm)
dtype: float64
NaN: 776
Unique: [0.0, 0.5, 1.0]
Non-zero: 825
Maximum: 1.0
Value counts:
1-minute Precipitation (mm)
0.0    315237
0.5       824
1.0         1
Name: count, dtype: int64

Precipitation Presence (Presence/Absence)
dtype: float64
NaN: 824
Unique: [0.0, 10.0]
Non-zero: 14123
Maximum: 10.0
Value counts:
Precipitation Presence (Presence/Absence)
0.0     301891
10.0     14123
Name: count, dtype: int64

In [8]:
from tqdm import tqdm

n_folds = (
    len(dates) - INITIAL_TRAIN_DAYS
    + TRAIN_INTERVAL_DAYS - 1
) // TRAIN_INTERVAL_DAYS

logging.info(
    f"Total observations: {len(df):,}"
)

logging.info(
    f"Total days: {len(dates)}"
)

logging.info(
    f"Total folds: {n_folds}"
)

logging.info(
    f"N_STATES={N_STATES}, "
    f"INITIAL_TRAIN_DAYS={INITIAL_TRAIN_DAYS}, "
    f"TRAIN_INTERVAL_DAYS={TRAIN_INTERVAL_DAYS}, "
    f"HORIZON={HORIZON}, "
    f"N_ITER={N_ITER}"
)
# ----------------------------------------
# Storage
# ----------------------------------------

all_results = []
metrics = []

previous_hmm = None

# ----------------------------------------
# Walk forward
# ----------------------------------------

train_end = INITIAL_TRAIN_DAYS
fold = 0

with tqdm(
    total=n_folds,
    desc="Walk-forward HMM",
    unit="fold"
) as pbar:
    while train_end < len(dates):
        fold += 1
        train_dates = dates[:train_end]

        eval_dates = dates[
            train_end:
            train_end + 1
        ]

        if not eval_dates:
            break

        # ------------------------------------------------
        # Progress description
        # ------------------------------------------------

        pbar.set_postfix_str(
            f"Train={train_dates[0]:%Y-%m-%d}"
            f"→{train_dates[-1]:%Y-%m-%d} | "
            f"Eval={eval_dates[0]:%Y-%m-%d}"
        )

        logging.info(
            f"Fold {fold}/{n_folds} | "
            f"Train: "
            f"{train_dates[0]:%Y-%m-%d}"
            f"→"
            f"{train_dates[-1]:%Y-%m-%d} | "
            f"Eval: "
            f"{eval_dates[0]:%Y-%m-%d}"
        )

        # ------------------------------------------------
        # Split
        # ------------------------------------------------

        train_df = df[
            df["_date"].isin(train_dates)
        ]

        #print(train_df)

        eval_df = df[
            df["_date"].isin(eval_dates)
        ]

        logging.info(
            f"Training rows: {len(train_df):,} | "
            f"Evaluation rows: {len(eval_df):,}"
        )

        # ------------------------------------------------
        # Train HMM
        # ------------------------------------------------

        hmm, scaler = train_hmm(
            train_df,
            previous_hmm=previous_hmm,
            n_states=N_STATES,
            n_iter=N_ITER,
        )

        logging.info(
            f"HMM trained | "
            f"iterations={hmm.monitor_.iter} | "
            f"converged={hmm.monitor_.converged}"
        )

        # ------------------------------------------------
        # State → rain mapping
        # ------------------------------------------------

        state_scores = learn_state_scores(
            train_df,
            hmm,
            scaler,
        )

        logging.info(
            "State rain scores: "
            + np.array2string(
                state_scores,
                precision=4
            )
        )

        # ------------------------------------------------
        # Evaluate
        # ------------------------------------------------

        result = evaluate_day(
            eval_df,
            hmm,
            scaler,
            state_scores,
        )

        result["Fold"] = fold
        result["Eval_Date"] = eval_dates[0]

        all_results.append(result)

        # ------------------------------------------------
        # Metrics
        # ------------------------------------------------

        fold_metrics = calculate_metrics(
            result
        )

        eval_start = eval_df["Date/Time"].min()
        eval_end = eval_df["Date/Time"].max()

        fold_metrics.update({
            "Fold": fold,
            "Eval_Date": eval_dates[0],
            "Train_Start": train_dates[0],
            "Train_End": train_dates[-1],
            "N_Train_Rows": len(train_df),
            "N_Eval_Rows": len(result),
        })

        metrics.append(
            fold_metrics
        )

        # ------------------------------------------------
        # Save metrics immediately
        # ------------------------------------------------

        metrics_df = pd.DataFrame(
            metrics
        )

        print(fold)
        save_evaluation_json(
            result=result,
            fold=fold,
            train_start=train_dates[0],
            train_end=train_dates[-1],
            eval_start=eval_start,
            eval_end=eval_end,
            metrics=metrics_df,
            output_dir="evaluation_logs",
        )

        metrics_df.to_csv(
            output_dir /
            "fold_metrics.csv",
            index=False
        )

        # ------------------------------------------------
        # Save current evaluation
        # ------------------------------------------------

        result.to_csv(
            output_dir /
            f"fold_{fold:03d}_evaluation.csv",
            index=False
        )

        # ------------------------------------------------
        # Log metrics
        # ------------------------------------------------

        logging.info(
            f"Fold {fold} metrics | "
            f"Brier={fold_metrics['Brier']:.4f} | "
            f"ROC-AUC={fold_metrics['ROC_AUC']:.4f} | "
            f"PR-AUC={fold_metrics['PR_AUC']:.4f} | "
            f"F1={fold_metrics['F1']:.4f}"
        )

        # ------------------------------------------------
        # Keep model
        # ------------------------------------------------

        previous_hmm = hmm

        # ------------------------------------------------
        # Advance by TRAIN_INTERVAL_DAYS
        # ------------------------------------------------

        #print(type(TRAIN_INTERVAL_DAYS), TRAIN_INTERVAL_DAYS)
        train_end += TRAIN_INTERVAL_DAYS

        pbar.update(1)

    # ========================================================
    # COMBINE RESULTS
    # ========================================================

    results_df = (
        pd.concat(
            all_results,
            ignore_index=True
        )
        if all_results
        else pd.DataFrame()
    )

    metrics_df = pd.DataFrame(
        metrics
    )

    results_df.to_csv(
        output_dir /
        "all_evaluation_results.csv",
        index=False
    )

    metrics_df.to_csv(
        output_dir /
        "fold_metrics.csv",
        index=False
    )

    if len(results_df) > 0:

        overall = calculate_metrics(
            results_df
        )

        overall_df = pd.DataFrame(
            [overall]
        )

        overall_df.to_csv(
            output_dir /
            "overall_metrics.csv",
            index=False
        )

        logging.info(
            f"Overall metrics | "
            f"Brier={overall['Brier']:.4f} | "
            f"ROC-AUC={overall['ROC_AUC']:.4f} | "
            f"PR-AUC={overall['PR_AUC']:.4f} | "
            f"F1={overall['F1']:.4f}"
        )

    logging.info(
        f"Experiment complete. "
        f"Results saved to: {output_dir}"
    )

2026-08-25 18:48:16,212 | INFO | Total observations: 316,838
2026-08-25 18:48:16,213 | INFO | Total days: 221
2026-08-25 18:48:16,214 | INFO | Total folds: 44
2026-08-25 18:48:16,215 | INFO | N_STATES=5, INITIAL_TRAIN_DAYS=5, TRAIN_INTERVAL_DAYS=5, HORIZON=5, N_ITER=50
Walk-forward HMM:   0%|          | 0/44 [00:00<?, ?fold/s, Train=2026-01-01→2026-01-05 | Eval=2026-01-06]2026-08-25 18:48:16,219 | INFO | Fold 1/44 | Train: 2026-01-01→2026-01-05 | Eval: 2026-01-06
2026-08-25 18:48:16,227 | INFO | Training rows: 7,198 | Evaluation rows: 1,440
2026-08-25 18:48:19,035 | INFO | HMM trained | iterations=38 | converged=True
2026-08-25 18:48:19,048 | INFO | State rain scores: [0. 0. 0. 0. 0.]

1

2026-08-25 18:48:19,376 | INFO | Fold 1 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   2%|▏         | 1/44 [00:03<02:15,  3.16s/fold, Train=2026-01-01→2026-01-10 | Eval=2026-01-11]2026-08-25 18:48:19,378 | INFO | Fold 2/44 | Train: 2026-01-01→2026-01-10 | Eval: 2026-01-11
2026-08-25 18:48:19,384 | INFO | Training rows: 14,398 | Evaluation rows: 1,440
2026-08-25 18:48:20,174 | WARNING | Model is not converging.  Current: 94728.33821162311 is not greater than 94728.34151927564. Delta is -0.003307652528746985
2026-08-25 18:48:20,175 | INFO | HMM trained | iterations=24 | converged=True
2026-08-25 18:48:20,193 | INFO | State rain scores: [0. 0. 0. 0. 0.]

2

2026-08-25 18:48:20,515 | INFO | Fold 2 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   5%|▍         | 2/44 [00:04<01:22,  1.97s/fold, Train=2026-01-01→2026-01-15 | Eval=2026-01-16]2026-08-25 18:48:20,517 | INFO | Fold 3/44 | Train: 2026-01-01→2026-01-15 | Eval: 2026-01-16
2026-08-25 18:48:20,524 | INFO | Training rows: 21,597 | Evaluation rows: 1,440
2026-08-25 18:48:21,741 | INFO | HMM trained | iterations=24 | converged=True
2026-08-25 18:48:21,765 | INFO | State rain scores: [0.0000e+00 0.0000e+00 5.5443e-04 0.0000e+00 6.7733e-01]

3

2026-08-25 18:48:22,092 | INFO | Fold 3 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   7%|▋         | 3/44 [00:05<01:13,  1.79s/fold, Train=2026-01-01→2026-01-20 | Eval=2026-01-21]2026-08-25 18:48:22,094 | INFO | Fold 4/44 | Train: 2026-01-01→2026-01-20 | Eval: 2026-01-21
2026-08-25 18:48:22,102 | INFO | Training rows: 28,797 | Evaluation rows: 1,440
2026-08-25 18:48:23,994 | INFO | HMM trained | iterations=32 | converged=True
2026-08-25 18:48:24,027 | INFO | State rain scores: [0.0000e+00 0.0000e+00 4.5196e-04 0.0000e+00 6.7733e-01]

4

2026-08-25 18:48:24,368 | INFO | Fold 4 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   9%|▉         | 4/44 [00:08<01:19,  1.98s/fold, Train=2026-01-01→2026-01-25 | Eval=2026-01-26]2026-08-25 18:48:24,370 | INFO | Fold 5/44 | Train: 2026-01-01→2026-01-25 | Eval: 2026-01-26
2026-08-25 18:48:24,381 | INFO | Training rows: 35,996 | Evaluation rows: 1,440
2026-08-25 18:48:26,987 | INFO | HMM trained | iterations=36 | converged=True
2026-08-25 18:48:27,024 | INFO | State rain scores: [0.0000e+00 0.0000e+00 3.2130e-04 0.0000e+00 6.7733e-01]

5

2026-08-25 18:48:27,351 | INFO | Fold 5 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  11%|█▏        | 5/44 [00:11<01:31,  2.34s/fold, Train=2026-01-01→2026-01-30 | Eval=2026-01-31]2026-08-25 18:48:27,353 | INFO | Fold 6/44 | Train: 2026-01-01→2026-01-30 | Eval: 2026-01-31
2026-08-25 18:48:27,363 | INFO | Training rows: 43,196 | Evaluation rows: 1,440
2026-08-25 18:48:31,744 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:48:31,790 | INFO | State rain scores: [0.     0.     0.     0.0034 0.6773]

6

2026-08-25 18:48:32,166 | INFO | Fold 6 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  14%|█▎        | 6/44 [00:15<02:00,  3.18s/fold, Train=2026-01-01→2026-02-04 | Eval=2026-02-05]2026-08-25 18:48:32,168 | INFO | Fold 7/44 | Train: 2026-01-01→2026-02-04 | Eval: 2026-02-05
2026-08-25 18:48:32,178 | INFO | Training rows: 50,395 | Evaluation rows: 1,439
2026-08-25 18:48:35,275 | INFO | HMM trained | iterations=30 | converged=True
2026-08-25 18:48:35,330 | INFO | State rain scores: [0.     0.     0.     0.0031 0.6773]

7

2026-08-25 18:48:35,661 | INFO | Fold 7 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  16%|█▌        | 7/44 [00:19<02:01,  3.29s/fold, Train=2026-01-01→2026-02-09 | Eval=2026-02-10]2026-08-25 18:48:35,663 | INFO | Fold 8/44 | Train: 2026-01-01→2026-02-09 | Eval: 2026-02-10
2026-08-25 18:48:35,674 | INFO | Training rows: 57,594 | Evaluation rows: 1,440
2026-08-25 18:48:41,457 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:48:41,523 | INFO | State rain scores: [5.6634e-04 0.0000e+00 0.0000e+00 3.3293e-03 6.1190e-01]

8

2026-08-25 18:48:41,853 | INFO | Fold 8 metrics | Brier=0.0280 | ROC-AUC=0.9591 | PR-AUC=0.6417 | F1=0.7722
Walk-forward HMM:  18%|█▊        | 8/44 [00:25<02:31,  4.21s/fold, Train=2026-01-01→2026-02-14 | Eval=2026-02-15]2026-08-25 18:48:41,855 | INFO | Fold 9/44 | Train: 2026-01-01→2026-02-14 | Eval: 2026-02-15
2026-08-25 18:48:41,867 | INFO | Training rows: 64,794 | Evaluation rows: 1,440
2026-08-25 18:48:48,340 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:48:48,407 | INFO | State rain scores: [4.0876e-04 4.6751e-04 1.3631e-04 3.5777e-03 6.0748e-01]

9

2026-08-25 18:48:48,739 | INFO | Fold 9 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  20%|██        | 9/44 [00:32<02:56,  5.05s/fold, Train=2026-01-01→2026-02-19 | Eval=2026-02-20]2026-08-25 18:48:48,741 | INFO | Fold 10/44 | Train: 2026-01-01→2026-02-19 | Eval: 2026-02-20
2026-08-25 18:48:48,753 | INFO | Training rows: 71,992 | Evaluation rows: 1,440
2026-08-25 18:48:56,241 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:48:56,320 | INFO | State rain scores: [5.1722e-04 3.7576e-04 8.6908e-05 3.0499e-03 5.3313e-01]

10

2026-08-25 18:48:56,656 | INFO | Fold 10 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  23%|██▎       | 10/44 [00:40<03:21,  5.93s/fold, Train=2026-01-01→2026-02-24 | Eval=2026-02-25]2026-08-25 18:48:56,657 | INFO | Fold 11/44 | Train: 2026-01-01→2026-02-24 | Eval: 2026-02-25
2026-08-25 18:48:56,670 | INFO | Training rows: 79,192 | Evaluation rows: 1,439
2026-08-25 18:49:05,006 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:49:05,086 | INFO | State rain scores: [7.6800e-04 4.2887e-04 2.0731e-04 0.0000e+00 8.4735e-01]

11

2026-08-25 18:49:05,417 | INFO | Fold 11 metrics | Brier=0.0046 | ROC-AUC=0.9660 | PR-AUC=0.7707 | F1=0.8732
Walk-forward HMM:  25%|██▌       | 11/44 [00:49<03:44,  6.80s/fold, Train=2026-01-01→2026-03-01 | Eval=2026-03-02]2026-08-25 18:49:05,419 | INFO | Fold 12/44 | Train: 2026-01-01→2026-03-01 | Eval: 2026-03-02
2026-08-25 18:49:05,436 | INFO | Training rows: 86,390 | Evaluation rows: 1,440
2026-08-25 18:49:10,464 | INFO | HMM trained | iterations=25 | converged=True
2026-08-25 18:49:10,571 | INFO | State rain scores: [8.0464e-04 2.7664e-04 1.1812e-04 0.0000e+00 8.7758e-01]

12

2026-08-25 18:49:10,911 | INFO | Fold 12 metrics | Brier=0.0293 | ROC-AUC=0.9448 | PR-AUC=0.9523 | F1=0.9738
Walk-forward HMM:  27%|██▋       | 12/44 [00:54<03:24,  6.40s/fold, Train=2026-01-01→2026-03-06 | Eval=2026-03-07]2026-08-25 18:49:10,913 | INFO | Fold 13/44 | Train: 2026-01-01→2026-03-06 | Eval: 2026-03-07
2026-08-25 18:49:10,935 | INFO | Training rows: 93,590 | Evaluation rows: 1,440
2026-08-25 18:49:16,108 | INFO | HMM trained | iterations=23 | converged=True
2026-08-25 18:49:16,209 | INFO | State rain scores: [1.4089e-03 2.6843e-04 0.0000e+00 0.0000e+00 8.7811e-01]

13

2026-08-25 18:49:16,562 | INFO | Fold 13 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  30%|██▉       | 13/44 [01:00<03:11,  6.17s/fold, Train=2026-01-01→2026-03-11 | Eval=2026-03-12]2026-08-25 18:49:16,563 | INFO | Fold 14/44 | Train: 2026-01-01→2026-03-11 | Eval: 2026-03-12
2026-08-25 18:49:16,580 | INFO | Training rows: 100,789 | Evaluation rows: 1,440
2026-08-25 18:49:26,984 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:49:27,091 | INFO | State rain scores: [1.2576e-03 2.4162e-04 0.0000e+00 0.0000e+00 8.7811e-01]

14

2026-08-25 18:49:27,421 | INFO | Fold 14 metrics | Brier=0.0186 | ROC-AUC=0.9637 | PR-AUC=0.5974 | F1=0.7376
Walk-forward HMM:  32%|███▏      | 14/44 [01:11<03:47,  7.59s/fold, Train=2026-01-01→2026-03-16 | Eval=2026-03-17]2026-08-25 18:49:27,423 | INFO | Fold 15/44 | Train: 2026-01-01→2026-03-16 | Eval: 2026-03-17
2026-08-25 18:49:27,443 | INFO | Training rows: 107,989 | Evaluation rows: 1,440
2026-08-25 18:49:38,472 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:49:38,578 | INFO | State rain scores: [1.5053e-03 2.1606e-04 0.0000e+00 6.1150e-04 8.4903e-01]

15

2026-08-25 18:49:39,002 | INFO | Fold 15 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  34%|███▍      | 15/44 [01:22<04:14,  8.79s/fold, Train=2026-01-01→2026-03-21 | Eval=2026-03-22]2026-08-25 18:49:39,004 | INFO | Fold 16/44 | Train: 2026-01-01→2026-03-21 | Eval: 2026-03-22
2026-08-25 18:49:39,022 | INFO | Training rows: 115,188 | Evaluation rows: 1,440
2026-08-25 18:49:50,653 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:49:50,758 | INFO | State rain scores: [1.3439e-03 6.9668e-04 0.0000e+00 5.8281e-04 8.5518e-01]

16

2026-08-25 18:49:51,087 | INFO | Fold 16 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  36%|███▋      | 16/44 [01:34<04:33,  9.78s/fold, Train=2026-01-01→2026-03-26 | Eval=2026-03-27]2026-08-25 18:49:51,088 | INFO | Fold 17/44 | Train: 2026-01-01→2026-03-26 | Eval: 2026-03-27
2026-08-25 18:49:51,106 | INFO | Training rows: 122,388 | Evaluation rows: 1,440
2026-08-25 18:50:03,029 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:50:03,147 | INFO | State rain scores: [1.2899e-03 7.4309e-04 0.0000e+00 1.7778e-03 8.4922e-01]

17

2026-08-25 18:50:03,473 | INFO | Fold 17 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  39%|███▊      | 17/44 [01:47<04:45, 10.57s/fold, Train=2026-01-01→2026-03-31 | Eval=2026-04-01]2026-08-25 18:50:03,475 | INFO | Fold 18/44 | Train: 2026-01-01→2026-03-31 | Eval: 2026-04-01
2026-08-25 18:50:03,494 | INFO | Training rows: 129,588 | Evaluation rows: 1,439
2026-08-25 18:50:15,066 | INFO | HMM trained | iterations=46 | converged=True
2026-08-25 18:50:15,191 | INFO | State rain scores: [1.7471e-03 7.4744e-04 0.0000e+00 2.7778e-03 8.5113e-01]

18

2026-08-25 18:50:15,518 | INFO | Fold 18 metrics | Brier=0.0086 | ROC-AUC=0.9472 | PR-AUC=0.6144 | F1=0.7708
Walk-forward HMM:  41%|████      | 18/44 [01:59<04:46, 11.01s/fold, Train=2026-01-01→2026-04-05 | Eval=2026-04-06]2026-08-25 18:50:15,520 | INFO | Fold 19/44 | Train: 2026-01-01→2026-04-05 | Eval: 2026-04-06
2026-08-25 18:50:15,539 | INFO | Training rows: 136,787 | Evaluation rows: 1,440
2026-08-25 18:50:25,259 | INFO | HMM trained | iterations=36 | converged=True
2026-08-25 18:50:25,390 | INFO | State rain scores: [1.7184e-03 7.9135e-04 0.0000e+00 2.7158e-03 8.6288e-01]

19

2026-08-25 18:50:25,723 | INFO | Fold 19 metrics | Brier=0.0235 | ROC-AUC=0.9288 | PR-AUC=0.4473 | F1=0.6316
Walk-forward HMM:  43%|████▎     | 19/44 [02:09<04:29, 10.77s/fold, Train=2026-01-01→2026-04-10 | Eval=2026-04-11]2026-08-25 18:50:25,725 | INFO | Fold 20/44 | Train: 2026-01-01→2026-04-10 | Eval: 2026-04-11
2026-08-25 18:50:25,745 | INFO | Training rows: 143,987 | Evaluation rows: 1,440
2026-08-25 18:50:39,774 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:50:39,894 | INFO | State rain scores: [2.2126e-03 7.5346e-04 0.0000e+00 1.4028e-03 8.5660e-01]

20

2026-08-25 18:50:40,220 | INFO | Fold 20 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  45%|████▌     | 20/44 [02:24<04:45, 11.89s/fold, Train=2026-01-01→2026-04-15 | Eval=2026-04-16]2026-08-25 18:50:40,222 | INFO | Fold 21/44 | Train: 2026-01-01→2026-04-15 | Eval: 2026-04-16
2026-08-25 18:50:40,241 | INFO | Training rows: 151,187 | Evaluation rows: 1,440
2026-08-25 18:50:54,920 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:50:55,050 | INFO | State rain scores: [2.0680e-03 7.7029e-04 1.0692e-04 1.4403e-03 8.5250e-01]

21

2026-08-25 18:50:55,379 | INFO | Fold 21 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  48%|████▊     | 21/44 [02:39<04:56, 12.87s/fold, Train=2026-01-01→2026-04-20 | Eval=2026-04-21]2026-08-25 18:50:55,381 | INFO | Fold 22/44 | Train: 2026-01-01→2026-04-20 | Eval: 2026-04-21
2026-08-25 18:50:55,401 | INFO | Training rows: 158,387 | Evaluation rows: 1,440
2026-08-25 18:51:11,652 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:51:11,867 | INFO | State rain scores: [2.4023e-03 4.8653e-04 0.0000e+00 1.4629e-03 8.4822e-01]

22

2026-08-25 18:51:12,231 | INFO | Fold 22 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  50%|█████     | 22/44 [02:56<05:09, 14.07s/fold, Train=2026-01-01→2026-04-25 | Eval=2026-04-26]2026-08-25 18:51:12,233 | INFO | Fold 23/44 | Train: 2026-01-01→2026-04-25 | Eval: 2026-04-26
2026-08-25 18:51:12,258 | INFO | Training rows: 165,586 | Evaluation rows: 1,440
2026-08-25 18:51:28,920 | INFO | HMM trained | iterations=45 | converged=True
2026-08-25 18:51:29,124 | INFO | State rain scores: [2.5879e-03 4.5941e-04 0.0000e+00 1.5184e-03 8.3272e-01]

23

2026-08-25 18:51:29,476 | INFO | Fold 23 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  52%|█████▏    | 23/44 [03:13<05:15, 15.02s/fold, Train=2026-01-01→2026-04-30 | Eval=2026-05-01]2026-08-25 18:51:29,478 | INFO | Fold 24/44 | Train: 2026-01-01→2026-04-30 | Eval: 2026-05-01
2026-08-25 18:51:29,522 | INFO | Training rows: 172,786 | Evaluation rows: 1,440
2026-08-25 18:51:48,206 | INFO | HMM trained | iterations=49 | converged=True
2026-08-25 18:51:48,389 | INFO | State rain scores: [2.5179e-03 6.2478e-04 0.0000e+00 1.3685e-03 8.3380e-01]

24

2026-08-25 18:51:48,724 | INFO | Fold 24 metrics | Brier=0.0533 | ROC-AUC=0.9179 | PR-AUC=0.7030 | F1=0.8228
Walk-forward HMM:  55%|█████▍    | 24/44 [03:32<05:25, 16.29s/fold, Train=2026-01-01→2026-05-05 | Eval=2026-05-06]2026-08-25 18:51:48,726 | INFO | Fold 25/44 | Train: 2026-01-01→2026-05-05 | Eval: 2026-05-06
2026-08-25 18:51:48,752 | INFO | Training rows: 179,986 | Evaluation rows: 1,440
2026-08-25 18:51:59,670 | INFO | HMM trained | iterations=29 | converged=True
2026-08-25 18:51:59,862 | INFO | State rain scores: [2.6710e-03 6.9777e-04 1.6179e-04 1.3449e-03 8.3326e-01]

25

2026-08-25 18:52:00,254 | INFO | Fold 25 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  57%|█████▋    | 25/44 [03:44<04:42, 14.86s/fold, Train=2026-01-01→2026-05-10 | Eval=2026-05-11]2026-08-25 18:52:00,256 | INFO | Fold 26/44 | Train: 2026-01-01→2026-05-10 | Eval: 2026-05-11
2026-08-25 18:52:00,281 | INFO | Training rows: 187,186 | Evaluation rows: 1,440
2026-08-25 18:52:16,014 | INFO | HMM trained | iterations=40 | converged=True
2026-08-25 18:52:16,212 | INFO | State rain scores: [2.1682e-03 1.6996e-03 1.4449e-04 1.2248e-03 8.3113e-01]

26

2026-08-25 18:52:16,540 | INFO | Fold 26 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  59%|█████▉    | 26/44 [04:00<04:35, 15.29s/fold, Train=2026-01-01→2026-05-15 | Eval=2026-05-16]2026-08-25 18:52:16,542 | INFO | Fold 27/44 | Train: 2026-01-01→2026-05-15 | Eval: 2026-05-16
2026-08-25 18:52:16,566 | INFO | Training rows: 194,385 | Evaluation rows: 1,439
2026-08-25 18:52:36,740 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:52:36,965 | INFO | State rain scores: [2.1238e-03 1.7519e-03 1.3846e-04 1.1986e-03 8.2836e-01]

27

2026-08-25 18:52:37,296 | INFO | Fold 27 metrics | Brier=0.0023 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  61%|██████▏   | 27/44 [04:21<04:47, 16.93s/fold, Train=2026-01-01→2026-05-20 | Eval=2026-05-21]2026-08-25 18:52:37,297 | INFO | Fold 28/44 | Train: 2026-01-01→2026-05-20 | Eval: 2026-05-21
2026-08-25 18:52:37,327 | INFO | Training rows: 201,583 | Evaluation rows: 1,440
2026-08-25 18:52:58,612 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:52:58,820 | INFO | State rain scores: [4.0691e-03 1.8496e-03 1.4122e-04 1.2670e-03 8.3623e-01]

28

2026-08-25 18:52:59,137 | INFO | Fold 28 metrics | Brier=0.0510 | ROC-AUC=0.9334 | PR-AUC=0.6703 | F1=0.7978
Walk-forward HMM:  64%|██████▎   | 28/44 [04:42<04:54, 18.40s/fold, Train=2026-01-01→2026-05-25 | Eval=2026-05-26]2026-08-25 18:52:59,139 | INFO | Fold 29/44 | Train: 2026-01-01→2026-05-25 | Eval: 2026-05-26
2026-08-25 18:52:59,165 | INFO | Training rows: 208,783 | Evaluation rows: 1,440
2026-08-25 18:53:20,988 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:53:21,225 | INFO | State rain scores: [4.0673e-03 2.1927e-03 1.2725e-04 1.0221e-03 8.3044e-01]

29

2026-08-25 18:53:21,560 | INFO | Fold 29 metrics | Brier=0.0063 | ROC-AUC=0.9958 | PR-AUC=0.9938 | F1=0.9937
Walk-forward HMM:  66%|██████▌   | 29/44 [05:05<04:54, 19.61s/fold, Train=2026-01-01→2026-05-30 | Eval=2026-05-31]2026-08-25 18:53:21,561 | INFO | Fold 30/44 | Train: 2026-01-01→2026-05-30 | Eval: 2026-05-31
2026-08-25 18:53:21,587 | INFO | Training rows: 215,983 | Evaluation rows: 1,440
2026-08-25 18:53:43,911 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:53:44,132 | INFO | State rain scores: [5.2997e-03 2.8316e-03 6.4329e-04 0.0000e+00 8.3133e-01]

30

2026-08-25 18:53:44,463 | INFO | Fold 30 metrics | Brier=0.0139 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  68%|██████▊   | 30/44 [05:28<04:48, 20.60s/fold, Train=2026-01-01→2026-06-04 | Eval=2026-06-05]2026-08-25 18:53:44,466 | INFO | Fold 31/44 | Train: 2026-01-01→2026-06-04 | Eval: 2026-06-05
2026-08-25 18:53:44,493 | INFO | Training rows: 223,183 | Evaluation rows: 1,440
2026-08-25 18:54:04,588 | INFO | HMM trained | iterations=43 | converged=True
2026-08-25 18:54:04,895 | INFO | State rain scores: [7.2403e-03 2.8552e-03 6.6977e-04 2.3102e-03 8.3814e-01]

31

2026-08-25 18:54:05,234 | INFO | Fold 31 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  70%|███████   | 31/44 [05:49<04:28, 20.65s/fold, Train=2026-01-01→2026-06-09 | Eval=2026-06-10]2026-08-25 18:54:05,235 | INFO | Fold 32/44 | Train: 2026-01-01→2026-06-09 | Eval: 2026-06-10
2026-08-25 18:54:05,271 | INFO | Training rows: 230,382 | Evaluation rows: 1,440
2026-08-25 18:54:29,331 | INFO | HMM trained | iterations=50 | converged=True
2026-08-25 18:54:29,580 | INFO | State rain scores: [7.0600e-03 2.9930e-03 6.7405e-04 2.2913e-03 8.3134e-01]

32

2026-08-25 18:54:29,915 | INFO | Fold 32 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  73%|███████▎  | 32/44 [06:13<04:22, 21.86s/fold, Train=2026-01-01→2026-06-14 | Eval=2026-06-15]2026-08-25 18:54:29,917 | INFO | Fold 33/44 | Train: 2026-01-01→2026-06-14 | Eval: 2026-06-15
2026-08-25 18:54:29,948 | INFO | Training rows: 237,582 | Evaluation rows: 1,440
2026-08-25 18:54:50,320 | INFO | HMM trained | iterations=41 | converged=True
2026-08-25 18:54:50,551 | INFO | State rain scores: [6.5328e-03 3.1669e-03 7.0001e-04 2.3729e-03 8.3134e-01]

33

2026-08-25 18:54:50,883 | INFO | Fold 33 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  75%|███████▌  | 33/44 [06:34<03:57, 21.59s/fold, Train=2026-01-01→2026-06-19 | Eval=2026-06-20]2026-08-25 18:54:50,885 | INFO | Fold 34/44 | Train: 2026-01-01→2026-06-19 | Eval: 2026-06-20
2026-08-25 18:54:50,917 | INFO | Training rows: 244,782 | Evaluation rows: 1,439
2026-08-25 18:55:07,341 | INFO | HMM trained | iterations=34 | converged=True
2026-08-25 18:55:07,562 | INFO | State rain scores: [7.6251e-03 2.9868e-03 7.0432e-04 2.2727e-03 8.2973e-01]
2026-08-25 18:55:07,742 | INFO | Fold 34 metrics | Brier=0.0518 | ROC-AUC=0.6167 | PR-AUC=0.9514 | F1=0.9723
Walk-forward HMM:  77%|███████▋  | 34/44 [06:51<03:21, 20.17s/fold, Train=2026-01-01→2026-06-24 | Eval=2026-06-25]2026-08-25 18:55:07,743 | INFO | Fold 35/44 | Train: 2026-01-01→2026-06-24 | Eval: 2026-06-25
2026-08-25 18:55:07,774 | INFO | Training rows: 251,980 | Evaluation rows: 1,440

34

2026-08-25 18:55:23,865 | INFO | HMM trained | iterations=32 | converged=True
2026-08-25 18:55:24,069 | INFO | State rain scores: [8.2117e-03 2.8993e-03 6.8961e-04 2.2117e-03 8.1907e-01]

35

2026-08-25 18:55:24,441 | INFO | Fold 35 metrics | Brier=0.0156 | ROC-AUC=0.9745 | PR-AUC=0.7616 | F1=0.8651
Walk-forward HMM:  80%|███████▉  | 35/44 [07:08<02:52, 19.13s/fold, Train=2026-01-01→2026-06-29 | Eval=2026-06-30]2026-08-25 18:55:24,443 | INFO | Fold 36/44 | Train: 2026-01-01→2026-06-29 | Eval: 2026-06-30
2026-08-25 18:55:24,474 | INFO | Training rows: 259,179 | Evaluation rows: 1,440
2026-08-25 18:55:38,617 | INFO | HMM trained | iterations=28 | converged=True
2026-08-25 18:55:38,854 | INFO | State rain scores: [7.9934e-03 2.8965e-03 6.7990e-04 2.1148e-03 8.1761e-01]

36

2026-08-25 18:55:39,184 | INFO | Fold 36 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  82%|████████▏ | 36/44 [07:22<02:22, 17.81s/fold, Train=2026-01-01→2026-07-04 | Eval=2026-07-05]2026-08-25 18:55:39,186 | INFO | Fold 37/44 | Train: 2026-01-01→2026-07-04 | Eval: 2026-07-05
2026-08-25 18:55:39,216 | INFO | Training rows: 266,379 | Evaluation rows: 1,439
2026-08-25 18:55:53,604 | INFO | HMM trained | iterations=27 | converged=True
2026-08-25 18:55:53,833 | INFO | State rain scores: [8.5604e-03 3.2396e-03 6.8187e-04 2.0927e-03 8.1761e-01]

37

2026-08-25 18:55:54,173 | INFO | Fold 37 metrics | Brier=0.0434 | ROC-AUC=0.9108 | PR-AUC=0.4468 | F1=0.6175
Walk-forward HMM:  84%|████████▍ | 37/44 [07:37<01:58, 16.97s/fold, Train=2026-01-01→2026-07-09 | Eval=2026-07-10]2026-08-25 18:55:54,175 | INFO | Fold 38/44 | Train: 2026-01-01→2026-07-09 | Eval: 2026-07-10
2026-08-25 18:55:54,210 | INFO | Training rows: 273,578 | Evaluation rows: 1,440
2026-08-25 18:56:08,420 | WARNING | Model is not converging.  Current: 2381231.286966364 is not greater than 2381231.2872177134. Delta is -0.0002513495273888111
2026-08-25 18:56:08,430 | INFO | HMM trained | iterations=25 | converged=True
2026-08-25 18:56:08,716 | INFO | State rain scores: [1.9025e-02 3.3074e-03 6.7378e-04 2.0468e-03 8.1435e-01]

38

2026-08-25 18:56:09,061 | INFO | Fold 38 metrics | Brier=0.1838 | ROC-AUC=0.6953 | PR-AUC=0.3840 | F1=0.0000
Walk-forward HMM:  86%|████████▋ | 38/44 [07:52<01:38, 16.34s/fold, Train=2026-01-01→2026-07-14 | Eval=2026-07-15]2026-08-25 18:56:09,063 | INFO | Fold 39/44 | Train: 2026-01-01→2026-07-14 | Eval: 2026-07-15
2026-08-25 18:56:09,093 | INFO | Training rows: 280,778 | Evaluation rows: 1,440
2026-08-25 18:56:23,843 | WARNING | Model is not converging.  Current: 2465332.0392958275 is not greater than 2465332.0393642057. Delta is -6.837816908955574e-05
2026-08-25 18:56:23,853 | INFO | HMM trained | iterations=26 | converged=True
2026-08-25 18:56:24,105 | INFO | State rain scores: [4.3321e-02 3.3888e-03 6.6961e-04 2.0202e-03 8.1264e-01]

39

2026-08-25 18:56:24,458 | INFO | Fold 39 metrics | Brier=0.2956 | ROC-AUC=0.5277 | PR-AUC=0.4918 | F1=0.0999
Walk-forward HMM:  89%|████████▊ | 39/44 [08:08<01:20, 16.06s/fold, Train=2026-01-01→2026-07-19 | Eval=2026-07-20]2026-08-25 18:56:24,460 | INFO | Fold 40/44 | Train: 2026-01-01→2026-07-19 | Eval: 2026-07-20
2026-08-25 18:56:24,496 | INFO | Training rows: 287,978 | Evaluation rows: 1,440
2026-08-25 18:56:39,636 | WARNING | Model is not converging.  Current: 2546630.2992955395 is not greater than 2546630.2996530593. Delta is -0.00035751983523368835
2026-08-25 18:56:39,647 | INFO | HMM trained | iterations=26 | converged=True
2026-08-25 18:56:39,898 | INFO | State rain scores: [6.3814e-02 4.7135e-03 6.6102e-04 1.9152e-03 8.1162e-01]

40

2026-08-25 18:56:40,228 | INFO | Fold 40 metrics | Brier=0.2884 | ROC-AUC=0.8340 | PR-AUC=0.7955 | F1=0.0857
Walk-forward HMM:  91%|█████████ | 40/44 [08:24<01:03, 15.97s/fold, Train=2026-01-01→2026-07-24 | Eval=2026-07-25]2026-08-25 18:56:40,230 | INFO | Fold 41/44 | Train: 2026-01-01→2026-07-24 | Eval: 2026-07-25
2026-08-25 18:56:40,264 | INFO | Training rows: 295,178 | Evaluation rows: 1,440
2026-08-25 18:57:01,992 | INFO | HMM trained | iterations=36 | converged=True
2026-08-25 18:57:02,334 | INFO | State rain scores: [8.9905e-02 1.0684e-02 6.6031e-04 3.3251e-03 8.1170e-01]

41

2026-08-25 18:57:02,679 | INFO | Fold 41 metrics | Brier=0.4843 | ROC-AUC=0.9285 | PR-AUC=0.9734 | F1=0.0000
Walk-forward HMM:  93%|█████████▎| 41/44 [08:46<00:53, 17.92s/fold, Train=2026-01-01→2026-07-29 | Eval=2026-07-30]2026-08-25 18:57:02,681 | INFO | Fold 42/44 | Train: 2026-01-01→2026-07-29 | Eval: 2026-07-30
2026-08-25 18:57:02,722 | INFO | Training rows: 302,378 | Evaluation rows: 1,440
2026-08-25 18:57:23,420 | WARNING | Model is not converging.  Current: 2721898.5400872948 is not greater than 2721898.540296814. Delta is -0.0002095191739499569
2026-08-25 18:57:23,431 | INFO | HMM trained | iterations=34 | converged=True
2026-08-25 18:57:23,767 | INFO | State rain scores: [1.1909e-01 2.5372e-02 6.6492e-04 3.1629e-03 8.1170e-01]

42

2026-08-25 18:57:24,120 | INFO | Fold 42 metrics | Brier=0.3633 | ROC-AUC=0.9192 | PR-AUC=0.8975 | F1=0.0000
Walk-forward HMM:  95%|█████████▌| 42/44 [09:07<00:37, 18.97s/fold, Train=2026-01-01→2026-08-03 | Eval=2026-08-04]2026-08-25 18:57:24,121 | INFO | Fold 43/44 | Train: 2026-01-01→2026-08-03 | Eval: 2026-08-04
2026-08-25 18:57:24,165 | INFO | Training rows: 309,578 | Evaluation rows: 1,440
2026-08-25 18:57:47,862 | INFO | HMM trained | iterations=37 | converged=True
2026-08-25 18:57:48,133 | INFO | State rain scores: [1.4541e-01 2.5853e-02 6.6876e-04 7.1533e-03 8.1170e-01]

43

2026-08-25 18:57:48,473 | INFO | Fold 43 metrics | Brier=0.2804 | ROC-AUC=0.9415 | PR-AUC=0.9365 | F1=0.0000
Walk-forward HMM:  98%|█████████▊| 43/44 [09:32<00:20, 20.59s/fold, Train=2026-01-01→2026-08-08 | Eval=2026-08-09]2026-08-25 18:57:48,474 | INFO | Fold 44/44 | Train: 2026-01-01→2026-08-08 | Eval: 2026-08-09
2026-08-25 18:57:48,514 | INFO | Training rows: 316,778 | Evaluation rows: 60
2026-08-25 18:58:10,001 | INFO | HMM trained | iterations=33 | converged=True
2026-08-25 18:58:10,298 | INFO | State rain scores: [1.6477e-01 2.4035e-02 6.5487e-04 1.3309e-02 8.1170e-01]
2026-08-25 18:58:10,331 | INFO | Fold 44 metrics | Brier=0.0012 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM: 100%|██████████| 44/44 [09:54<00:00, 20.97s/fold, Train=2026-01-01→2026-08-08 | Eval=2026-08-09]

44

2026-08-25 18:58:11,910 | INFO | Overall metrics | Brier=0.0522 | ROC-AUC=0.9728 | PR-AUC=0.7946 | F1=0.5401
2026-08-25 18:58:11,911 | INFO | Experiment complete. Results saved to: results
Walk-forward HMM: 100%|██████████| 44/44 [09:55<00:00, 13.54s/fold, Train=2026-01-01→2026-08-08 | Eval=2026-08-09]

In [9]:
train_df

,Station,Date/Time,Temperature (°C),1-minute Precipitation (mm),Precipitation Presence (Presence/Absence),Wind Direction (deg),Wind Speed (m/s),Local Pressure (hPa),Sea-level Pressure (hPa),Humidity (%),...,humidity_change_5min,pressure_change_5min,wind_change_5min,rain_5min,future_rain_score,effective_heat,heat_score,future_heat_score,future_open_score,_date
0,939,2026-01-01 00:01:00,-2.8,0.0,0.0,81.2,1.7,1017.5,1023.8,21.1,...,0.0,0.0,0.0,0.0,0.0,-5.69,0.000000,0.000000,0.000000,2026-01-01
1,939,2026-01-01 00:02:00,-2.8,0.0,0.0,88.1,2.2,1017.5,1023.8,21.1,...,0.0,0.0,0.0,0.0,0.0,-5.69,0.000000,0.000000,0.000000,2026-01-01
2,939,2026-01-01 00:03:00,-3.0,0.0,0.0,95.1,1.4,1017.5,1023.8,21.4,...,0.0,0.0,0.0,0.0,0.0,-5.86,0.000000,0.000000,0.000000,2026-01-01
3,939,2026-01-01 00:04:00,-3.0,0.0,0.0,80.9,1.8,1017.4,1023.7,21.7,...,0.0,0.0,0.0,0.0,0.0,-5.83,0.000000,0.000000,0.000000,2026-01-01
4,939,2026-01-01 00:05:00,-2.9,0.0,0.0,66.4,0.9,1017.4,1023.7,21.8,...,0.0,0.0,0.0,0.0,0.0,-5.72,0.000000,0.000000,0.000000,2026-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316773,939,2026-08-08 23:55:00,28.1,0.0,0.0,52.3,2.7,1001.5,1007,65.7,...,0.1,0.0,0.4,0.0,0.0,29.67,0.209159,0.196261,0.196261,2026-08-08
316774,939,2026-08-08 23:56:00,28.1,0.0,0.0,32.2,2.5,1001.5,1007,65.0,...,-0.6,0.0,0.7,0.0,0.0,29.60,0.197816,0.195007,0.195007,2026-08-08
316775,939,2026-08-08 23:57:00,28.1,0.0,0.0,30.0,2.6,1001.5,1007,65.3,...,-0.4,0.0,-0.4,0.0,0.0,29.63,0.202620,0.195007,0.195007,2026-08-08
316776,939,2026-08-08 23:58:00,28.1,0.0,0.0,50.5,4.0,1001.5,1007,64.8,...,-0.8,0.0,1.0,0.0,0.0,29.58,0.194662,0.197248,0.197248,2026-08-08
316777,939,2026-08-08 23:59:00,28.1,0.0,0.0,27.9,2.1,1001.4,1006.9,64.8,...,-0.6,-0.2,-2.3,0.0,0.0,29.58,0.194662,0.199164,0.199164,2026-08-08